// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteResponse_Stream int32

const (
	ExecuteResponse_STDOUT ExecuteResponse_Stream = 0
	ExecuteResponse_STDERR ExecuteResponse_Stream = 1
)

// Enum value maps for ExecuteResponse_Stream.
var (
	ExecuteResponse_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecuteResponse_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecuteResponse_Stream) Enum() *ExecuteResponse_Stream {
	p := new(ExecuteResponse_Stream)
	*p = x
	return p
}

func (x ExecuteResponse_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteResponse_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (ExecuteResponse_Stream) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[0]
}

func (x ExecuteResponse_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteResponse_Stream.Descriptor instead.
func (ExecuteResponse_Stream) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2, 0}
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Shell          string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"` // "powershell", "cmd", "bash" (auto-detect if empty)
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = no timeout
	Detach         bool                   `protobuf:"varint,6,opt,name=detach,proto3" json:"detach,omitempty"`                                       // Start detached (survives agent restart)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *ExecuteRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteRequest) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

type ExecuteScriptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScriptBody     string                 `protobuf:"bytes,1,opt,name=script_body,json=scriptBody,proto3" json:"script_body,omitempty"` // Inline script content
	Shell          string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`                             // "powershell", "bash" (auto-detect if empty)
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Args           []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"` // Script arguments
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteScriptRequest) Reset() {
	*x = ExecuteScriptRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScriptRequest) ProtoMessage() {}

func (x *ExecuteScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScriptRequest.ProtoReflect.Descriptor instead.
func (*ExecuteScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteScriptRequest) GetScriptBody() string {
	if x != nil {
		return x.ScriptBody
	}
	return ""
}

func (x *ExecuteScriptRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *ExecuteScriptRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteScriptRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteScriptRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteScriptRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        ExecuteResponse_Stream `protobuf:"varint,1,opt,name=stream,proto3,enum=agent.ExecuteResponse_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // Valid when done=true
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                           // PID of spawned process (sent in first message)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetStream() ExecuteResponse_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecuteResponse_STDOUT
}

func (x *ExecuteResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type PushFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"` // Destination path on the agent node
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`                             // File data chunk (64KB)
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`            // True for the final chunk
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`      // Total size (sent in first message, 0 if unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFileRequest) Reset() {
	*x = PushFileRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileRequest) ProtoMessage() {}

func (x *PushFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileRequest.ProtoReflect.Descriptor instead.
func (*PushFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PushFileRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *PushFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *PushFileRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *PushFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type PushFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFileResponse) Reset() {
	*x = PushFileResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileResponse) ProtoMessage() {}

func (x *PushFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileResponse.ProtoReflect.Descriptor instead.
func (*PushFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PushFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *PushFileResponse) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type PullFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"` // File path on the agent node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullFileRequest) Reset() {
	*x = PullFileRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileRequest) ProtoMessage() {}

func (x *PullFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileRequest.ProtoReflect.Descriptor instead.
func (*PullFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PullFileRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type PullFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`                           // File data chunk
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // Total file size (sent in first message)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullFileResponse) Reset() {
	*x = PullFileResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileResponse) ProtoMessage() {}

func (x *PullFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileResponse.ProtoReflect.Descriptor instead.
func (*PullFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PullFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *PullFileResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type ListProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameFilter    string                 `protobuf:"bytes,1,opt,name=name_filter,json=nameFilter,proto3" json:"name_filter,omitempty"` // Optional substring filter on process name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListProcessesRequest) GetNameFilter() string {
	if x != nil {
		return x.NameFilter
	}
	return ""
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommandLine   string                 `protobuf:"bytes,3,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ProcessInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

type KillProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // SIGKILL / TerminateProcess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *KillProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *KillProcessRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type KillProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *KillProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`     // "windows" or "linux"
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"` // "amd64", "arm64"
	CpuCount      int32                  `protobuf:"varint,4,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *GetInfoResponse) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *GetInfoResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GetInfoResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\x8c\x02\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x120\n" +
	"\x03env\x18\x04 \x03(\v2\x1e.agent.ExecuteRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x16\n" +
	"\x06detach\x18\x06 \x01(\bR\x06detach\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\x14ExecuteScriptRequest\x12\x1f\n" +
	"\vscript_body\x18\x01 \x01(\tR\n" +
	"scriptBody\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x126\n" +
	"\x03env\x18\x04 \x03(\v2$.agent.ExecuteScriptRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0fExecuteResponse\x125\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1d.agent.ExecuteResponse.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"~\n" +
	"\x0fPushFileRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\"X\n" +
	"\x10PushFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\"2\n" +
	"\x0fPullFileRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\"G\n" +
	"\x10PullFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"7\n" +
	"\x14ListProcessesRequest\x12\x1f\n" +
	"\vname_filter\x18\x01 \x01(\tR\n" +
	"nameFilter\"I\n" +
	"\x15ListProcessesResponse\x120\n" +
	"\tprocesses\x18\x01 \x03(\v2\x12.agent.ProcessInfoR\tprocesses\"\x9a\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcommand_line\x18\x03 \x01(\tR\vcommandLine\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\"<\n" +
	"\x12KillProcessRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"I\n" +
	"\x13KillProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eGetInfoRequest\"\xb6\x01\n" +
	"\x0fGetInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_count\x18\x04 \x01(\x05R\bcpuCount\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion2\xd9\x03\n" +
	"\tNodeAgent\x12:\n" +
	"\aExecute\x12\x15.agent.ExecuteRequest\x1a\x16.agent.ExecuteResponse0\x01\x12F\n" +
	"\rExecuteScript\x12\x1b.agent.ExecuteScriptRequest\x1a\x16.agent.ExecuteResponse0\x01\x12=\n" +
	"\bPushFile\x12\x16.agent.PushFileRequest\x1a\x17.agent.PushFileResponse(\x01\x12=\n" +
	"\bPullFile\x12\x16.agent.PullFileRequest\x1a\x17.agent.PullFileResponse0\x01\x12J\n" +
	"\rListProcesses\x12\x1b.agent.ListProcessesRequest\x1a\x1c.agent.ListProcessesResponse\x12D\n" +
	"\vKillProcess\x12\x19.agent.KillProcessRequest\x1a\x1a.agent.KillProcessResponse\x128\n" +
	"\aGetInfo\x12\x15.agent.GetInfoRequest\x1a\x16.agent.GetInfoResponseB*Z(github.com/nijosmsft/lablink/proto/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_agent_agent_proto_goTypes = []any{
	(ExecuteResponse_Stream)(0),   // 0: agent.ExecuteResponse.Stream
	(*ExecuteRequest)(nil),        // 1: agent.ExecuteRequest
	(*ExecuteScriptRequest)(nil),  // 2: agent.ExecuteScriptRequest
	(*ExecuteResponse)(nil),       // 3: agent.ExecuteResponse
	(*PushFileRequest)(nil),       // 4: agent.PushFileRequest
	(*PushFileResponse)(nil),      // 5: agent.PushFileResponse
	(*PullFileRequest)(nil),       // 6: agent.PullFileRequest
	(*PullFileResponse)(nil),      // 7: agent.PullFileResponse
	(*ListProcessesRequest)(nil),  // 8: agent.ListProcessesRequest
	(*ListProcessesResponse)(nil), // 9: agent.ListProcessesResponse
	(*ProcessInfo)(nil),           // 10: agent.ProcessInfo
	(*KillProcessRequest)(nil),    // 11: agent.KillProcessRequest
	(*KillProcessResponse)(nil),   // 12: agent.KillProcessResponse
	(*GetInfoRequest)(nil),        // 13: agent.GetInfoRequest
	(*GetInfoResponse)(nil),       // 14: agent.GetInfoResponse
	nil,                           // 15: agent.ExecuteRequest.EnvEntry
	nil,                           // 16: agent.ExecuteScriptRequest.EnvEntry
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	15, // 0: agent.ExecuteRequest.env:type_name -> agent.ExecuteRequest.EnvEntry
	16, // 1: agent.ExecuteScriptRequest.env:type_name -> agent.ExecuteScriptRequest.EnvEntry
	0,  // 2: agent.ExecuteResponse.stream:type_name -> agent.ExecuteResponse.Stream
	10, // 3: agent.ListProcessesResponse.processes:type_name -> agent.ProcessInfo
	1,  // 4: agent.NodeAgent.Execute:input_type -> agent.ExecuteRequest
	2,  // 5: agent.NodeAgent.ExecuteScript:input_type -> agent.ExecuteScriptRequest
	4,  // 6: agent.NodeAgent.PushFile:input_type -> agent.PushFileRequest
	6,  // 7: agent.NodeAgent.PullFile:input_type -> agent.PullFileRequest
	8,  // 8: agent.NodeAgent.ListProcesses:input_type -> agent.ListProcessesRequest
	11, // 9: agent.NodeAgent.KillProcess:input_type -> agent.KillProcessRequest
	13, // 10: agent.NodeAgent.GetInfo:input_type -> agent.GetInfoRequest
	3,  // 11: agent.NodeAgent.Execute:output_type -> agent.ExecuteResponse
	3,  // 12: agent.NodeAgent.ExecuteScript:output_type -> agent.ExecuteResponse
	5,  // 13: agent.NodeAgent.PushFile:output_type -> agent.PushFileResponse
	7,  // 14: agent.NodeAgent.PullFile:output_type -> agent.PullFileResponse
	9,  // 15: agent.NodeAgent.ListProcesses:output_type -> agent.ListProcessesResponse
	12, // 16: agent.NodeAgent.KillProcess:output_type -> agent.KillProcessResponse
	14, // 17: agent.NodeAgent.GetInfo:output_type -> agent.GetInfoResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
