// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgent_Execute_FullMethodName       = "/agent.NodeAgent/Execute"
	NodeAgent_ExecuteScript_FullMethodName = "/agent.NodeAgent/ExecuteScript"
	NodeAgent_PushFile_FullMethodName      = "/agent.NodeAgent/PushFile"
	NodeAgent_PullFile_FullMethodName      = "/agent.NodeAgent/PullFile"
	NodeAgent_ListProcesses_FullMethodName = "/agent.NodeAgent/ListProcesses"
	NodeAgent_KillProcess_FullMethodName   = "/agent.NodeAgent/KillProcess"
	NodeAgent_GetInfo_FullMethodName       = "/agent.NodeAgent/GetInfo"
	NodeAgent_ListJobs_FullMethodName      = "/agent.NodeAgent/ListJobs"
	NodeAgent_GetJob_FullMethodName        = "/agent.NodeAgent/GetJob"
	NodeAgent_GetJobOutput_FullMethodName  = "/agent.NodeAgent/GetJobOutput"
	NodeAgent_CancelJob_FullMethodName     = "/agent.NodeAgent/CancelJob"
	NodeAgent_DeleteJob_FullMethodName     = "/agent.NodeAgent/DeleteJob"
	NodeAgent_WatchJobs_FullMethodName     = "/agent.NodeAgent/WatchJobs"
	NodeAgent_Forward_FullMethodName       = "/agent.NodeAgent/Forward"
)

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentClient interface {
	// Execute a command and stream stdout/stderr back in real-time.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
	// Execute an inline script (pushed as temp file, executed, cleaned up).
	ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
	// Push a file from MCP server to the agent node.
	PushFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushFileRequest, PushFileResponse], error)
	// Pull a file from the agent node to the MCP server.
	PullFile(ctx context.Context, in *PullFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullFileResponse], error)
	// List running processes.
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	// Kill a process by PID.
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error)
	// Health check and node metadata.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// List tracked background jobs (detached executions).
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// Get a single job's metadata.
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// Get captured output for a job (stdout and/or stderr).
	GetJobOutput(ctx context.Context, in *GetJobOutputRequest, opts ...grpc.CallOption) (*GetJobOutputResponse, error)
	// Cancel a running job (terminates the process tree).
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// Delete a terminal job (removes the job directory).
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error)
	// Watch job lifecycle events. On connect, the agent replays a snapshot of
	// current jobs as Started events, then streams live updates.
	WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// Forward TCP bytes bidirectionally between the operator and a target on
	// the agent node. The first client message MUST set target_addr; the agent
	// dials it (TCP) and then byte-shuttles in both directions. Either side
	// sends {close: true} to signal half-close. Used to tunnel application
	// protocols (e.g. an MCP server bound to localhost on the node) through the
	// node agent's existing mTLS channel.
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardChunk, ForwardChunk], error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[0], NodeAgent_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_ExecuteClient = grpc.ServerStreamingClient[ExecuteResponse]

func (c *nodeAgentClient) ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[1], NodeAgent_ExecuteScript_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteScriptRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_ExecuteScriptClient = grpc.ServerStreamingClient[ExecuteResponse]

func (c *nodeAgentClient) PushFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushFileRequest, PushFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[2], NodeAgent_PushFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushFileRequest, PushFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_PushFileClient = grpc.ClientStreamingClient[PushFileRequest, PushFileResponse]

func (c *nodeAgentClient) PullFile(ctx context.Context, in *PullFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[3], NodeAgent_PullFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullFileRequest, PullFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_PullFileClient = grpc.ServerStreamingClient[PullFileResponse]

func (c *nodeAgentClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillProcessResponse)
	err := c.cc.Invoke(ctx, NodeAgent_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetJobOutput(ctx context.Context, in *GetJobOutputRequest, opts ...grpc.CallOption) (*GetJobOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobOutputResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetJobOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[4], NodeAgent_WatchJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobsRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_WatchJobsClient = grpc.ServerStreamingClient[JobEvent]

func (c *nodeAgentClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardChunk, ForwardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[5], NodeAgent_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardChunk, ForwardChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_ForwardClient = grpc.BidiStreamingClient[ForwardChunk, ForwardChunk]

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility.
type NodeAgentServer interface {
	// Execute a command and stream stdout/stderr back in real-time.
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	// Execute an inline script (pushed as temp file, executed, cleaned up).
	ExecuteScript(*ExecuteScriptRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	// Push a file from MCP server to the agent node.
	PushFile(grpc.ClientStreamingServer[PushFileRequest, PushFileResponse]) error
	// Pull a file from the agent node to the MCP server.
	PullFile(*PullFileRequest, grpc.ServerStreamingServer[PullFileResponse]) error
	// List running processes.
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	// Kill a process by PID.
	KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error)
	// Health check and node metadata.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// List tracked background jobs (detached executions).
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// Get a single job's metadata.
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// Get captured output for a job (stdout and/or stderr).
	GetJobOutput(context.Context, *GetJobOutputRequest) (*GetJobOutputResponse, error)
	// Cancel a running job (terminates the process tree).
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// Delete a terminal job (removes the job directory).
	DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error)
	// Watch job lifecycle events. On connect, the agent replays a snapshot of
	// current jobs as Started events, then streams live updates.
	WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[JobEvent]) error
	// Forward TCP bytes bidirectionally between the operator and a target on
	// the agent node. The first client message MUST set target_addr; the agent
	// dials it (TCP) and then byte-shuttles in both directions. Either side
	// sends {close: true} to signal half-close. Used to tunnel application
	// protocols (e.g. an MCP server bound to localhost on the node) through the
	// node agent's existing mTLS channel.
	Forward(grpc.BidiStreamingServer[ForwardChunk, ForwardChunk]) error
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServer struct{}

func (UnimplementedNodeAgentServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNodeAgentServer) ExecuteScript(*ExecuteScriptRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteScript not implemented")
}
func (UnimplementedNodeAgentServer) PushFile(grpc.ClientStreamingServer[PushFileRequest, PushFileResponse]) error {
	return status.Error(codes.Unimplemented, "method PushFile not implemented")
}
func (UnimplementedNodeAgentServer) PullFile(*PullFileRequest, grpc.ServerStreamingServer[PullFileResponse]) error {
	return status.Error(codes.Unimplemented, "method PullFile not implemented")
}
func (UnimplementedNodeAgentServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedNodeAgentServer) KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedNodeAgentServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedNodeAgentServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedNodeAgentServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedNodeAgentServer) GetJobOutput(context.Context, *GetJobOutputRequest) (*GetJobOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobOutput not implemented")
}
func (UnimplementedNodeAgentServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedNodeAgentServer) DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedNodeAgentServer) WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchJobs not implemented")
}
func (UnimplementedNodeAgentServer) Forward(grpc.BidiStreamingServer[ForwardChunk, ForwardChunk]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}
func (UnimplementedNodeAgentServer) testEmbeddedByValue()                   {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_ExecuteServer = grpc.ServerStreamingServer[ExecuteResponse]

func _NodeAgent_ExecuteScript_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteScriptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).ExecuteScript(m, &grpc.GenericServerStream[ExecuteScriptRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_ExecuteScriptServer = grpc.ServerStreamingServer[ExecuteResponse]

func _NodeAgent_PushFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).PushFile(&grpc.GenericServerStream[PushFileRequest, PushFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_PushFileServer = grpc.ClientStreamingServer[PushFileRequest, PushFileResponse]

func _NodeAgent_PullFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).PullFile(m, &grpc.GenericServerStream[PullFileRequest, PullFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_PullFileServer = grpc.ServerStreamingServer[PullFileResponse]

func _NodeAgent_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetJobOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetJobOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetJobOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetJobOutput(ctx, req.(*GetJobOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteJob(ctx, req.(*DeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_WatchJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).WatchJobs(m, &grpc.GenericServerStream[WatchJobsRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_WatchJobsServer = grpc.ServerStreamingServer[JobEvent]

func _NodeAgent_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).Forward(&grpc.GenericServerStream[ForwardChunk, ForwardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_ForwardServer = grpc.BidiStreamingServer[ForwardChunk, ForwardChunk]

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProcesses",
			Handler:    _NodeAgent_ListProcesses_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _NodeAgent_KillProcess_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _NodeAgent_GetInfo_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _NodeAgent_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _NodeAgent_GetJob_Handler,
		},
		{
			MethodName: "GetJobOutput",
			Handler:    _NodeAgent_GetJobOutput_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _NodeAgent_CancelJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _NodeAgent_DeleteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _NodeAgent_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteScript",
			Handler:       _NodeAgent_ExecuteScript_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushFile",
			Handler:       _NodeAgent_PushFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullFile",
			Handler:       _NodeAgent_PullFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchJobs",
			Handler:       _NodeAgent_WatchJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _NodeAgent_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/agent.proto",
}
